### ISSUE TITLE
🐞 Publishing updated Excel file fails

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/voc4cat#43]
### Observed in version

irrelevant (v_de8f110f)

### Description

Recently we added generation of rdf/xml in addition to turtle (#35). However, the presence of the 2nd format now causes an error (https://github.com/nfdi4cat/voc4cat/actions/runs/7756154205/job/21152918529):

```
INFO    |Executing cmd: voc4cat convert --logfile publish/dev/voc4cat.log --template templates/voc4cat_template_043.xlsx publish/dev/
DEBUG   |Processing common options.
DEBUG   |Convert subcommand started!
ERROR   |Files may only be present in one format. Found more than one format for: "publish/dev/voc4cat"
ERROR   |Terminating with Voc4cat error.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 450, in run_cli_app
    main_cli(raw_args)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 442, in main_cli
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/convert.py", line 424, in convert
    _check_convert_args(args)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/convert.py", line 418, in _check_convert_args
    raise Voc4catError(msg % '", "'.join(duplicates))
voc4cat.checks.Voc4catError: Files may only be present in one format. Found more than one format for: "publish/dev/voc4cat"
```

**Comment by dalito** [comment]
A missing clean-up for the new xml files caused this issue.
