### ISSUE TITLE
🐞 CI failed because orcid id was missing

### ISSUE THREAD

**Issue by RoteKekse** [nfdi4cat/voc4cat#56]
### Description

Hey, i created an orcid id now: 0009-0008-1278-8890

can you add that to my id range. Without the orcid the CI fails.

```
Run # convert file(s) from xlsx in inbox to turtle in outbox
INFO    |Executing cmd: voc4cat convert --config _main_branch/idranges.toml --logfile outbox/voc4cat.log --outdir outbox inbox-excel-vocabs/
DEBUG   |Processing common options.
DEBUG   |Config loaded from: _main_branch/idranges.toml
DEBUG   |Convert subcommand started!
DEBUG   |Processing "inbox-excel-vocabs/voc4cat.xlsx"
DEBUG   |-> Validating ID range config for vocabulary "voc4cat".
ERROR   |Terminating with Voc4cat error.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/convert_043.py", line 88, in extract_concepts_and_collections
    c = models.Concept(**concept_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Concept
__root__
  ID of IRI https://w3id.org/nfdi4cat/voc4cat_0007201 is not in allowed ID range(s) of actor "0009-0008-1278-8890" (from provenance). (type=value_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 450, in run_cli_app
    main_cli(raw_args)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 442, in main_cli
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/convert.py", line 444, in convert
    excel_to_rdf(file, output_file_path, output_format=args.outputformat)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/convert.py", line 132, in excel_to_rdf
    concepts, collections = extract_concepts_and_collections_043(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/convert_043.py", line 91, in extract_concepts_and_collections
    raise ConversionError(msg) from exc
voc4cat.utils.ConversionError: Concept processing error likely at sheet <Worksheet "Concepts">, row 192, and has error: 1 validation error for Concept
__root__
  ID of IRI https://w3id.org/nfdi4cat/voc4cat_0007201 is not in allowed ID range(s) of actor "0009-0008-1278-8890" (from provenance). (type=value_error)
Error: Process completed with exit code 1.
```

Best
Micha

**Comment by RoteKekse** [comment]
Hey it seems to also missing the ror? https://ror.org/02aj13c28
or else i am not understanding the error message in the MR?
